package com.joxad.zikobot.app.youtube.download;

import android.os.Bundle;

import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBase;
import com.joxad.zikobot.app.BR;
import com.joxad.zikobot.app.R;
import com.joxad.zikobot.app.core.utils.EXTRA;
import com.joxad.zikobot.app.databinding.FragmentDownloadBinding;
import com.joxad.zikobot.data.module.youtube.VideoItem;

/**
 * Generated by generator-android-template
 */
public class FragmentDownload extends DialogBottomSheetBase<FragmentDownloadBinding, FragmentDownloadVM> {


    public static FragmentDownload newInstance(VideoItem model) {
        Bundle args = new Bundle();
        FragmentDownload fragment = new FragmentDownload();
        args.putParcelable(EXTRA.VIDEO, model);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public int data() {
        return BR.fragmentDownloadVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.fragment_download;
    }

    @Override
    public FragmentDownloadVM baseFragmentVM(FragmentDownloadBinding binding) {
        return new FragmentDownloadVM(this, binding);
    }


    /**
     * Use this part if you want to put the dialog fullscreen
     @Override public Dialog onCreateDialog(Bundle savedInstanceState) {
     BottomSheetDialog dialog = (BottomSheetDialog) super.onCreateDialog(savedInstanceState);
     dialog.setOnShowListener(dialog1 -> {
     BottomSheetDialog d = (BottomSheetDialog) dialog1;
     FrameLayout bottomSheet = (FrameLayout) d.findViewById(android.support.design.R.id.design_bottom_sheet);
     BottomSheetBehavior<FrameLayout> bot = BottomSheetBehavior.from(bottomSheet);
     bot.setState(BottomSheetBehavior.STATE_EXPANDED);
     bottomSheet.setBackgroundColor(ContextCompat.getColor(getActivity(), android.R.color.transparent));

     });
     return dialog;
     }
     */
}
