package com.startogamu.zikobot.search

import com.joxad.easydatabinding.activity.ActivityBaseVM
import com.startogamu.zikobot.R
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.databinding.SearchActivityBinding

import android.os.Bundle

/**
 * Generated by generator-android-template
 */
class SearchActivityVM
/***
 * @param activity
 * *
 * @param binding
 */
(activity: SearchActivity, binding: SearchActivityBinding, savedInstance: Bundle?) : ActivityBaseVM<SearchActivity, SearchActivityBinding>(activity, binding, savedInstance) {

    override fun onCreate(savedInstance: Bundle?) {

    }

    companion object {

        private val TAG = SearchActivityVM::class.java.simpleName
    }
}
