package com.startogamu.zikobot.search;

import com.joxad.easydatabinding.activity.ActivityBaseVM;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.SearchActivityBinding;

import android.os.Bundle;
import android.support.annotation.Nullable;
/**
 * Generated by generator-android-template
 */
public class SearchActivityVM extends ActivityBaseVM<SearchActivity, SearchActivityBinding> {

  private static final String TAG = SearchActivityVM.class.getSimpleName();
  /***
    * @param activity
    * @param binding
    */
   public SearchActivityVM(SearchActivity activity, SearchActivityBinding binding,@Nullable Bundle savedInstance) {
       super(activity, binding, savedInstance);
   }

   @Override
   public void onCreate(@Nullable Bundle savedInstance) {

   }
}
