package com.startogamu.zikobot.search;

import com.joxad.easydatabinding.activity.ActivityBase;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.SearchActivityBinding;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
/**
 * Generated by generator-android-template
 */
public class SearchActivity extends ActivityBase<SearchActivityBinding, SearchActivityVM> {
    @Override
    public int data() {
        return BR.searchActivityVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.search_activity;
    }

    @Override
    public SearchActivityVM baseActivityVM(SearchActivityBinding binding, Bundle savedInstanceState) {
        return new SearchActivityVM(this, binding,savedInstanceState);
    }

    /***
     * Generate the intent for the activity
     * Use this to start the activity
     */
    public static Intent newInstance(Context context) {
        return new Intent(context, SearchActivity.class);
    }
}
