package com.joxad.zikobot.app.youtube;

import com.joxad.easydatabinding.fragment.v4.FragmentBase;
import com.joxad.zikobot.app.R;
import com.joxad.zikobot.app.BR;
import com.joxad.zikobot.app.databinding.FragmentYoutubeSearchBinding;
import android.os.Bundle;

/**
 * Generated by generator-android-template
 */
public class FragmentYoutubeSearch extends FragmentBase<FragmentYoutubeSearchBinding, FragmentYoutubeSearchVM> {


  public static FragmentYoutubeSearch newInstance() {
       Bundle args = new Bundle();
       FragmentYoutubeSearch fragment = new FragmentYoutubeSearch();
       fragment.setArguments(args);
       return fragment;
   }
    @Override
    public int data() {
        return BR.fragmentYoutubeSearchVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.fragment_youtube_search;
    }

    @Override
    public FragmentYoutubeSearchVM baseFragmentVM(FragmentYoutubeSearchBinding binding) {
        return new FragmentYoutubeSearchVM(this, binding);
    }
}
