package com.startogamu.zikobot.home.reco;

import com.joxad.easydatabinding.fragment.v4.FragmentBase;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.RecoFragmentBinding;
import android.os.Bundle;

import android.support.annotation.Nullable;
/**
 * Generated by generator-android-template
 */
public class RecoFragment extends FragmentBase<RecoFragmentBinding, RecoFragmentVM> {


  public static RecoFragment newInstance() {
       Bundle args = new Bundle();
       RecoFragment fragment = new RecoFragment();
       fragment.setArguments(args);
       return fragment;
   }
    @Override
    public int data() {
        return BR.recoFragmentVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.reco_fragment;
    }

    @Override
    public RecoFragmentVM baseFragmentVM(RecoFragmentBinding binding,@Nullable Bundle savedInstance) {
        return new RecoFragmentVM(this, binding,savedInstance);
    }
}
