package com.startogamu.zikobot.home.reco;

import android.os.Bundle;
import android.support.annotation.Nullable;

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM;
import com.startogamu.zikobot.databinding.RecoFragmentBinding;

/**
 * Generated by generator-android-template
 */
public class RecoFragmentVM extends FragmentBaseVM<RecoFragment, RecoFragmentBinding> {

    private static final String TAG = RecoFragmentVM.class.getSimpleName();

    /***
     * @param fragment
     * @param binding
     */
    public RecoFragmentVM(RecoFragment fragment, RecoFragmentBinding binding, @Nullable Bundle savedInstance) {
        super(fragment, binding, savedInstance);
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstance) {

    }
}
