package com.startogamu.zikobot.home.playlists

import android.os.Bundle

import com.joxad.easydatabinding.fragment.v4.FragmentBase
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.PlaylistsFragmentBinding

/**
 * Generated by generator-android-template
 */
class PlaylistsFragment : FragmentBase<PlaylistsFragmentBinding, PlaylistsFragmentVM>() {

    override fun data(): Int {
        return BR.playlistsFragmentVM
    }

    override fun layoutResources(): Int {
        return R.layout.playlists_fragment
    }

    override fun baseFragmentVM(binding: PlaylistsFragmentBinding, savedInstance: Bundle?): PlaylistsFragmentVM {
        return PlaylistsFragmentVM(this, binding, savedInstance)
    }

    companion object {
        fun newInstance(): PlaylistsFragment {
            val args = Bundle()
            val fragment = PlaylistsFragment()
            fragment.arguments = args
            return fragment
        }
    }
}
