package com.startogamu.zikobot.home.playlists

import com.joxad.easydatabinding.activity.ActivityBase
import com.startogamu.zikobot.Constants
import com.startogamu.zikobot.R
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.databinding.PlaylistDetailActivityBinding

import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.view.Menu

/**
 * Generated by generator-android-template
 */
class PlaylistDetailActivity : ActivityBase<PlaylistDetailActivityBinding, PlaylistDetailActivityVM>() {
    override fun data(): Int {
        return BR.playlistDetailActivityVM
    }

    override fun layoutResources(): Int {
        return R.layout.playlist_detail_activity
    }

    override fun baseActivityVM(binding: PlaylistDetailActivityBinding, savedInstanceState: Bundle?): PlaylistDetailActivityVM {
        return PlaylistDetailActivityVM(this, binding, savedInstanceState)
    }

    override fun onCreateOptionsMenu(menu: Menu?): Boolean {
        menuInflater.inflate(R.menu.menu_playlist, menu)
        return true
    }

    companion object {

        /***
         * Generate the intent for the activity
         * Use this to start the activity
         */
        fun newInstance(context: Context, playlistId: Long): Intent {
            return Intent(context, PlaylistDetailActivity::class.java)
                    .putExtra(Constants.Extra.PLAYLIST_ID, playlistId)
        }
    }
}
