package com.startogamu.zikobot.home.playlists

import android.databinding.ObservableArrayList
import android.os.Bundle
import com.joxad.androidtemplate.core.log.AppLog
import com.joxad.easydatabinding.activity.ActivityBaseVM
import com.joxad.zikobot.data.db.PlaylistManager
import com.joxad.zikobot.data.db.model.ZikoTrack
import com.joxad.zikobot.data.module.spotify_api.manager.SpotifyApiManager
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.Constants
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.PlaylistDetailActivityBinding
import me.tatarka.bindingcollectionadapter2.ItemBinding

/**
 * Generated by generator-android-template
 */
class PlaylistDetailActivityVM
/***
 * @param activity
 * *
 * @param binding
 */
(activity: PlaylistDetailActivity, binding: PlaylistDetailActivityBinding, savedInstance: Bundle?) : ActivityBaseVM<PlaylistDetailActivity, PlaylistDetailActivityBinding>(activity, binding, savedInstance) {

    lateinit var items: ObservableArrayList<TrackVM>
    var itemBinding = ItemBinding.of<TrackVM>(BR.trackVM, R.layout.track_item)
    lateinit var playlistVM: PlaylistVM
    override fun onCreate(saved: Bundle?) {
        items = ObservableArrayList<TrackVM>()

        loadData()
    }

    /***
     * Load the data from WS or DB to show them in the recycler
     */
    fun loadData() {
        val pId = activity.intent.getLongExtra(Constants.Extra.PLAYLIST_ID, 0)
        PlaylistManager.findOne(pId)
                .querySingle().subscribe({ zi ->
            playlistVM = PlaylistVM(false, activity, zi)
            SpotifyApiManager.INSTANCE.getPlaylistTracks(playlistVM.model.spotifyId, 0, 50)
                    .subscribe({
                        for (track in it.items)
                            items.add(TrackVM(activity, ZikoTrack.from(track.track)))
                    }, {
                        AppLog.INSTANCE.e("Spotify", it.localizedMessage)
                    })
        })


    }

    /***
     * Add one mode o
     */
    private fun addVM(vm: TrackVM) {
        items.add(vm)
    }

    companion object {

        private val TAG = PlaylistDetailActivityVM::class.java.simpleName
    }


}
