package com.startogamu.zikobot.home.playlists;

import android.os.Bundle;

import com.joxad.easydatabinding.fragment.v4.FragmentBase;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.databinding.PlaylistsFragmentBinding;

/**
 * Generated by generator-android-template
 */
public class PlaylistsFragment extends FragmentBase<PlaylistsFragmentBinding, PlaylistsFragmentVM> {


    public static PlaylistsFragment newInstance() {
        Bundle args = new Bundle();
        PlaylistsFragment fragment = new PlaylistsFragment();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public int data() {
        return BR.playlistsFragmentVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.playlists_fragment;
    }

    @Override
    public PlaylistsFragmentVM baseFragmentVM(PlaylistsFragmentBinding binding, Bundle savedInstance) {
        return new PlaylistsFragmentVM(this, binding, savedInstance);
    }
}
