package com.startogamu.zikobot.home.playlists;

import android.os.Bundle;
import android.support.annotation.Nullable;

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM;
import com.startogamu.zikobot.databinding.PlaylistsFragmentBinding;
//TODO update template with bundle

/**
 * Generated by generator-android-template
 */
public class PlaylistsFragmentVM extends FragmentBaseVM<PlaylistsFragment, PlaylistsFragmentBinding> {

    private static final String TAG = PlaylistsFragmentVM.class.getSimpleName();

    /***
     * @param fragment
     * @param binding
     */
    public PlaylistsFragmentVM(PlaylistsFragment fragment, PlaylistsFragmentBinding binding, @Nullable Bundle savedInstance) {
        super(fragment, binding, savedInstance);
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstance) {

    }
}
