package com.startogamu.zikobot.home.playlists

import android.os.Bundle

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM
import com.startogamu.zikobot.databinding.PlaylistsFragmentBinding

/**
 * Generated by generator-android-template
 */
class PlaylistsFragmentVM(fragment: PlaylistsFragment, binding: PlaylistsFragmentBinding, savedInstance: Bundle?)
    : FragmentBaseVM<PlaylistsFragment, PlaylistsFragmentBinding>(fragment, binding, savedInstance) {

    override fun onCreate(savedInstance: Bundle?) {

    }

    companion object {

        private val TAG = PlaylistsFragmentVM::class.java.simpleName
    }
}
