package com.startogamu.zikobot.home.sync

import android.databinding.ObservableArrayList
import android.os.Bundle
import com.joxad.androidtemplate.core.log.AppLog
import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBaseVM
import com.joxad.zikobot.data.db.model.ZikoPlaylist
import com.joxad.zikobot.data.module.spotify_api.manager.SpotifyApiManager
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.SpotifySyncPlaylistsFragmentBinding
import com.startogamu.zikobot.home.playlists.PlaylistVM
import me.tatarka.bindingcollectionadapter2.ItemBinding

/**
 * Generated by generator-android-template
 */
class SpotifySyncPlaylistsFragmentVM(fragment: SpotifySyncPlaylistsFragment, binding: SpotifySyncPlaylistsFragmentBinding) : DialogBottomSheetBaseVM<SpotifySyncPlaylistsFragment, SpotifySyncPlaylistsFragmentBinding>(fragment, binding) {


    var itemBinding = ItemBinding.of<PlaylistVM>(BR.playlistVM, R.layout.playlist_item)
    lateinit var items: ObservableArrayList<PlaylistVM>


    override fun onCreate() {

        items = ObservableArrayList()

        SpotifyApiManager.INSTANCE.userPlaylists.subscribe({
            for (spo in it.items) {
                val zikoP = ZikoPlaylist.fromSpotifyPlaylist(spo)
                items.add(PlaylistVM(false, fragment.activity, zikoP))
            }
        }, {
            AppLog.INSTANCE.e("Spotify", it.localizedMessage)
        })
        //PlaylistManager.syncSpotify().subscribe({
        //loadPlaylists()
        //}, {
        // AppLog.INSTANCE.e("Spotify", it.localizedMessage)
        //})
    }

    override fun onCreate(savedInstance: Bundle?) {

    }

    companion object {

        val TAG = SpotifySyncPlaylistsFragmentVM::class.java.simpleName
    }
}
