package com.startogamu.zikobot.home.sync;

import android.app.Dialog;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.BottomSheetBehavior;
import android.support.design.widget.BottomSheetDialog;
import android.widget.FrameLayout;

import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBase;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.databinding.SpotifySyncPlaylistsFragmentBinding;

/**
 * Generated by generator-android-template
 */
public class SpotifySyncPlaylistsFragment extends DialogBottomSheetBase<SpotifySyncPlaylistsFragmentBinding, SpotifySyncPlaylistsFragmentVM> {


    public static SpotifySyncPlaylistsFragment newInstance() {
        Bundle args = new Bundle();
        SpotifySyncPlaylistsFragment fragment = new SpotifySyncPlaylistsFragment();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public int data() {
        return BR.spotifySyncPlaylistsFragmentVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.spotify_sync_playlists_fragment;
    }

    @Override
    public SpotifySyncPlaylistsFragmentVM baseFragmentVM(SpotifySyncPlaylistsFragmentBinding binding) {
        return new SpotifySyncPlaylistsFragmentVM(this, binding);
    }

    @NonNull
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        BottomSheetDialog dialog = (BottomSheetDialog) super.onCreateDialog(savedInstanceState);
        dialog.setOnShowListener(dialog1 -> {
            BottomSheetDialog d = (BottomSheetDialog) dialog1;
            FrameLayout bottomSheet = (FrameLayout) d.findViewById(android.support.design.R.id.design_bottom_sheet);
            BottomSheetBehavior<FrameLayout> bot = BottomSheetBehavior.from(bottomSheet);
            bot.setState(BottomSheetBehavior.STATE_EXPANDED);

        });
        return dialog;
    }
}
