package com.startogamu.zikobot.home.create

import android.os.Bundle
import android.view.KeyEvent
import android.view.View
import android.view.inputmethod.EditorInfo
import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBaseVM
import com.joxad.zikobot.data.db.PlaylistManager
import com.joxad.zikobot.data.db.model.ZikoPlaylist
import com.raizlabs.android.dbflow.kotlinextensions.save
import com.startogamu.zikobot.databinding.CreatePlaylistFragmentBinding

/**
 * Generated by generator-android-template
 */
class CreatePlaylistFragmentVM(fragment: CreatePlaylistFragment, binding: CreatePlaylistFragmentBinding) : DialogBottomSheetBaseVM<CreatePlaylistFragment, CreatePlaylistFragmentBinding>(fragment, binding) {

//TODO handle case when there is a long press on a track and no playlist or if user choose create new playlist from playlist selection
    override fun onCreate() {

        binding.createPlaylistEt.requestFocus()
        binding.createPlaylistEt.setOnEditorActionListener({
            tv,action,event ->
            if (action== EditorInfo.IME_ACTION_DONE)
                savePlaylist(null)
            return@setOnEditorActionListener false
        })
    }


    override fun onCreate(savedInstance: Bundle?) {

    }

    fun savePlaylist(view: View?) {
        PlaylistManager.INSTANCE.save(ZikoPlaylist(binding.createPlaylistEt.text.toString()))
        fragment.dismiss()
    }

    companion object {

        val TAG = CreatePlaylistFragmentVM::class.java.simpleName
    }
}