package com.startogamu.zikobot.home.create;

import android.app.Dialog;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.BottomSheetBehavior;
import android.support.design.widget.BottomSheetDialog;
import android.widget.FrameLayout;

import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBase;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.databinding.CreatePlaylistFragmentBinding;
import com.startogamu.zikobot.home.sync.SpotifySyncPlaylistsFragmentVM;

/**
 * Generated by generator-android-template
 */
public class CreatePlaylistFragment extends DialogBottomSheetBase<CreatePlaylistFragmentBinding, CreatePlaylistFragmentVM> {


    public static CreatePlaylistFragment newInstance() {
        Bundle args = new Bundle();
        CreatePlaylistFragment fragment = new CreatePlaylistFragment();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public int data() {
        return BR.fragmentVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.create_playlist_fragment;
    }

    @Override
    public CreatePlaylistFragmentVM baseFragmentVM(CreatePlaylistFragmentBinding binding) {
        return new CreatePlaylistFragmentVM(this, binding);
    }

    @NonNull
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        BottomSheetDialog dialog = (BottomSheetDialog) super.onCreateDialog(savedInstanceState);
        dialog.setOnShowListener(dialog1 -> {
            BottomSheetDialog d = (BottomSheetDialog) dialog1;
            FrameLayout bottomSheet = (FrameLayout) d.findViewById(android.support.design.R.id.design_bottom_sheet);
            BottomSheetBehavior<FrameLayout> bot = BottomSheetBehavior.from(bottomSheet);
            bot.setState(BottomSheetBehavior.STATE_EXPANDED);

        });
        return dialog;
    }
}
