package com.startogamu.zikobot.home.artists

import android.os.Bundle
import com.joxad.easydatabinding.fragment.v4.FragmentBase
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.Constants
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.AlbumsArtistFragmentBinding

/**
 * Generated by generator-android-template
 */
class AlbumsArtistFragment : FragmentBase<AlbumsArtistFragmentBinding, AlbumsArtistFragmentVM>() {
    override fun data(): Int {
        return BR.albumsArtistFragmentVM
    }

    override fun layoutResources(): Int {
        return R.layout.albums_artist_fragment
    }

    override fun baseFragmentVM(binding: AlbumsArtistFragmentBinding, savedInstance: Bundle?): AlbumsArtistFragmentVM {
        return AlbumsArtistFragmentVM(this, binding, savedInstance)
    }

    companion object {


        fun newInstance(artistId: Int): AlbumsArtistFragment {
            val args = Bundle()
            args.putInt(Constants.Extra.ARTIST_ID, artistId)
            val fragment = AlbumsArtistFragment()
            fragment.arguments = args
            return fragment
        }
    }
}
