package com.startogamu.zikobot.home.artists;

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.AlbumsArtistFragmentBinding;
import com.startogamu.zikobot.home.artists.AlbumsArtistFragment;

import android.os.Bundle;
import android.support.annotation.Nullable;

/**
 * Generated by generator-android-template
 */
public class AlbumsArtistFragmentVM extends FragmentBaseVM<AlbumsArtistFragment, AlbumsArtistFragmentBinding> {

  private static final String TAG = AlbumsArtistFragmentVM.class.getSimpleName();

  /***
    * @param fragment
    * @param binding
    */
   public AlbumsArtistFragmentVM(AlbumsArtistFragment fragment, AlbumsArtistFragmentBinding binding,@Nullable Bundle savedInstance) {
       super(fragment, binding, savedInstance);
   }

   @Override
   public void onCreate(@Nullable Bundle savedInstance) {

   }
}
