package com.startogamu.zikobot.home.artists;

import com.joxad.easydatabinding.fragment.v4.FragmentBase;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.AlbumsArtistFragmentBinding;
import android.os.Bundle;

import android.support.annotation.Nullable;
/**
 * Generated by generator-android-template
 */
public class AlbumsArtistFragment extends FragmentBase<AlbumsArtistFragmentBinding, AlbumsArtistFragmentVM> {


  public static AlbumsArtistFragment newInstance() {
       Bundle args = new Bundle();
       AlbumsArtistFragment fragment = new AlbumsArtistFragment();
       fragment.setArguments(args);
       return fragment;
   }
    @Override
    public int data() {
        return BR.albumsArtistFragmentVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.albums_artist_fragment;
    }

    @Override
    public AlbumsArtistFragmentVM baseFragmentVM(AlbumsArtistFragmentBinding binding,@Nullable Bundle savedInstance) {
        return new AlbumsArtistFragmentVM(this, binding,savedInstance);
    }
}
