package com.startogamu.zikobot.home.artists

import android.os.Bundle

import com.joxad.easydatabinding.fragment.v4.FragmentBase
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.ArtistsFragmentBinding

/**
 * Generated by generator-android-template
 */
class ArtistsFragment : FragmentBase<ArtistsFragmentBinding, ArtistsFragmentVM>() {

    override fun data(): Int {
        return BR.artistsFragmentVM
    }

    override fun layoutResources(): Int {
        return R.layout.artists_fragment
    }

    override fun baseFragmentVM(binding: ArtistsFragmentBinding, savedInstance: Bundle?): ArtistsFragmentVM {
        return ArtistsFragmentVM(this, binding, savedInstance)
    }

    companion object {


        fun newInstance(): ArtistsFragment {
            val args = Bundle()
            val fragment = ArtistsFragment()
            fragment.arguments = args
            return fragment
        }
    }
}
