package com.startogamu.zikobot.home.artists

import android.databinding.ObservableArrayList
import android.os.Bundle
import com.joxad.androidtemplate.core.log.AppLog
import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM
import com.joxad.zikobot.data.db.ArtistManager
import com.joxad.zikobot.data.db.CurrentPlaylistManager
import com.joxad.zikobot.data.db.TrackManager
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.Constants
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.ArtistHomeFragmentBinding
import com.startogamu.zikobot.home.track.TrackVM
import me.tatarka.bindingcollectionadapter2.ItemBinding

/**
 * Generated by generator-android-template
 */
class ArtistHomeFragmentVM
/***
 * @param fragment
 * @param binding
 */
(fragment: ArtistHomeFragment, binding: ArtistHomeFragmentBinding, savedInstance: Bundle?) : FragmentBaseVM<ArtistHomeFragment, ArtistHomeFragmentBinding>(fragment, binding, savedInstance) {


    var artistId: Int = 0
    lateinit var items: ObservableArrayList<TrackVM>
    var itemBinding = ItemBinding.of<TrackVM>(BR.trackVM, R.layout.track_item)


    override fun onCreate(savedInstance: Bundle?) {
        artistId = fragment.arguments.getInt(Constants.Extra.ARTIST_ID)
        items = ObservableArrayList()

        ArtistManager.findOne(artistId).subscribe({ it ->
            if (!it.spotifyId.isNullOrEmpty())
                loadTracks(it.spotifyId!!)
        }, {
            AppLog.INSTANCE.e(ArtistHomeFragmentVM.TAG, it.localizedMessage)
        })
    }


    private fun loadTracks(artistId: String) {
        TrackManager.findTopTracksFromAPI(artistId)
                .subscribe({
                    for (zT in it) {
                            items.add(TrackVM(fragment.context, zT))
                    }
                }, {
                    AppLog.INSTANCE.e("Add track", it.localizedMessage)
                })
    }


    companion object {

        private val TAG = ArtistHomeFragmentVM::class.java.simpleName
    }

}
