package com.startogamu.zikobot.home.artists;

import android.content.Context;

import com.joxad.easydatabinding.base.BaseVM;
import com.joxad.zikobot.data.db.model.ZikoArtist;

/**
 * Generated by generator-android-template
 * <!!!!!> You have to replace the Object to your POJO class that will be handled in the VM <!!!!!>
 */
public class ArtistVM extends BaseVM<ZikoArtist> {

    /***
     * @param context
     * @param model
     */
    public ArtistVM(Context context, ZikoArtist model) {
        super(context, model);
    }

    @Override
    public void onCreate() {

    }
}
