package com.startogamu.zikobot.home.artists;

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.ArtistHomeFragmentBinding;
import com.startogamu.zikobot.home.artists.ArtistHomeFragment;

import android.os.Bundle;
import android.support.annotation.Nullable;

/**
 * Generated by generator-android-template
 */
public class ArtistHomeFragmentVM extends FragmentBaseVM<ArtistHomeFragment, ArtistHomeFragmentBinding> {

  private static final String TAG = ArtistHomeFragmentVM.class.getSimpleName();

  /***
    * @param fragment
    * @param binding
    */
   public ArtistHomeFragmentVM(ArtistHomeFragment fragment, ArtistHomeFragmentBinding binding,@Nullable Bundle savedInstance) {
       super(fragment, binding, savedInstance);
   }

   @Override
   public void onCreate(@Nullable Bundle savedInstance) {

   }
}
