package com.startogamu.zikobot.home.artists

import android.content.Context
import android.content.Intent
import android.os.Bundle

import com.joxad.easydatabinding.activity.ActivityBase
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.Constants
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.ArtistDetailActivityBinding

/**
 * Generated by generator-android-template
 */
class ArtistDetailActivity : ActivityBase<ArtistDetailActivityBinding, ArtistDetailActivityVM>() {
    override fun data(): Int {
        return BR.artistDetailActivityVM
    }

    override fun layoutResources(): Int {
        return R.layout.artist_detail_activity
    }

    override fun baseActivityVM(binding: ArtistDetailActivityBinding, savedInstanceState: Bundle?): ArtistDetailActivityVM {
        return ArtistDetailActivityVM(this, binding, savedInstanceState)
    }

    companion object {

        /***
         * Generate the intent for the activity
         * Use this to start the activity
         */
        fun newInstance(context: Context, artistId: Int): Intent {
            return Intent(context, ArtistDetailActivity::class.java)
                    .putExtra(Constants.Extra.ARTIST_ID, artistId)
        }
    }
}
