package com.startogamu.zikobot.home.artists;

import android.os.Bundle;
import android.support.annotation.Nullable;

import com.joxad.easydatabinding.fragment.v4.FragmentBase;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.databinding.ArtistsFragmentBinding;

/**
 * Generated by generator-android-template
 */
public class ArtistsFragment extends FragmentBase<ArtistsFragmentBinding, ArtistsFragmentVM> {


    public static ArtistsFragment newInstance() {
        Bundle args = new Bundle();
        ArtistsFragment fragment = new ArtistsFragment();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public int data() {
        return BR.artistsFragmentVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.artists_fragment;
    }

    @Override
    public ArtistsFragmentVM baseFragmentVM(ArtistsFragmentBinding binding, @Nullable Bundle savedInstance) {
        return new ArtistsFragmentVM(this, binding, savedInstance);
    }
}
