package com.startogamu.zikobot.home.artists;

import android.databinding.ObservableArrayList;
import android.os.Bundle;
import android.support.annotation.Nullable;

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM;
import com.joxad.zikobot.data.db.model.ZikoArtist;
import com.startogamu.zikobot.databinding.SimilarArtistsFragmentBinding;

/**
 * Generated by generator-android-template
 */
public class SimilarArtistsFragmentVM extends FragmentBaseVM<SimilarArtistsFragment, SimilarArtistsFragmentBinding> {

    private static final String TAG = SimilarArtistsFragmentVM.class.getSimpleName();

    public ObservableArrayList<ZikoArtist> items;

    /***
     * @param fragment
     * @param binding
     */
    public SimilarArtistsFragmentVM(SimilarArtistsFragment fragment, SimilarArtistsFragmentBinding binding, @Nullable Bundle savedInstance) {
        super(fragment, binding, savedInstance);
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstance) {
        items = new ObservableArrayList<>();
    }
}
