package com.startogamu.zikobot.home.artists;

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.SimilarArtistsFragmentBinding;
import com.startogamu.zikobot.home.artists.SimilarArtistsFragment;

import android.os.Bundle;
import android.support.annotation.Nullable;

/**
 * Generated by generator-android-template
 */
public class SimilarArtistsFragmentVM extends FragmentBaseVM<SimilarArtistsFragment, SimilarArtistsFragmentBinding> {

  private static final String TAG = SimilarArtistsFragmentVM.class.getSimpleName();

  /***
    * @param fragment
    * @param binding
    */
   public SimilarArtistsFragmentVM(SimilarArtistsFragment fragment, SimilarArtistsFragmentBinding binding,@Nullable Bundle savedInstance) {
       super(fragment, binding, savedInstance);
   }

   @Override
   public void onCreate(@Nullable Bundle savedInstance) {

   }
}
