package com.startogamu.zikobot.home.artists

import android.databinding.ObservableArrayList
import android.os.Bundle
import android.support.v7.widget.RecyclerView
import com.joxad.androidtemplate.core.log.AppLog
import com.joxad.androidtemplate.core.view.utils.EndlessRecyclerOnScrollListener
import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM
import com.joxad.zikobot.data.db.ArtistManager
import com.joxad.zikobot.data.db.CurrentPlaylistManager
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.Constants
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.TracksArtistFragmentBinding
import com.startogamu.zikobot.home.track.TrackVM
import me.tatarka.bindingcollectionadapter2.ItemBinding

/**
 * Generated by generator-android-template
 */
class TracksArtistFragmentVM
/***
 * @param fragment
 * @param binding
 */
(fragment: TracksArtistFragment, binding: TracksArtistFragmentBinding, savedInstance: Bundle?) : FragmentBaseVM<TracksArtistFragment, TracksArtistFragmentBinding>(fragment, binding, savedInstance) {


    var artistId: Int = 0
    lateinit var items: ObservableArrayList<TrackVM>
    var itemBinding = ItemBinding.of<TrackVM>(BR.trackVM, R.layout.track_item)

    override fun onCreate(savedInstance: Bundle?) {
        artistId = fragment.arguments.getInt(Constants.Extra.ARTIST_ID)
        items = ObservableArrayList()
        addTracks(artistId,0)
        binding.artistDetailActivityRv.addOnScrollListener(object : EndlessRecyclerOnScrollListener() {
            override fun onLoadMore(page: Int, totalItemsCount: Int, view: RecyclerView?) {
                addTracks(artistId, page)
            }
        })
    }

    private fun addTracks(artistId: Int, indexStart: Int) {
        ArtistManager.findTracks(artistId, indexStart)
                .subscribe({
                    for (zT in it) {
                        if (zT.zikoPlaylist.id != CurrentPlaylistManager.INSTANCE.CURRENT)
                            items.add(TrackVM(fragment.context, zT))
                    }
                }, {
                    AppLog.INSTANCE.e("Add track", it.localizedMessage)
                })
    }

    companion object {

        private val TAG = TracksArtistFragmentVM::class.java.simpleName
    }
}
