package com.startogamu.zikobot.home.artists;

import com.joxad.easydatabinding.fragment.v4.FragmentBase;
import com.startogamu.zikobot.Constants;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.TracksArtistFragmentBinding;
import android.os.Bundle;

import android.support.annotation.Nullable;
/**
 * Generated by generator-android-template
 */
public class TracksArtistFragment extends FragmentBase<TracksArtistFragmentBinding, TracksArtistFragmentVM> {


  public static TracksArtistFragment newInstance(int id) {
       Bundle args = new Bundle();
       args.putInt(Constants.Extra.INSTANCE.getARTIST_ID(), id);
       TracksArtistFragment fragment = new TracksArtistFragment();
       fragment.setArguments(args);
       return fragment;
   }
    @Override
    public int data() {
        return BR.tracksArtistFragmentVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.tracks_artist_fragment;
    }

    @Override
    public TracksArtistFragmentVM baseFragmentVM(TracksArtistFragmentBinding binding,@Nullable Bundle savedInstance) {
        return new TracksArtistFragmentVM(this, binding,savedInstance);
    }
}
