package com.startogamu.zikobot.ftu

import android.os.Bundle
import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBaseVM
import com.joxad.zikobot.data.AppPrefs
import com.startogamu.zikobot.databinding.AccountLinkFragmentBinding

/**
 * Generated by generator-android-template
 */
class AccountLinkFragmentVM(fragment: AccountLinkFragment, binding: AccountLinkFragmentBinding) :
        DialogBottomSheetBaseVM<AccountLinkFragment, AccountLinkFragmentBinding>(fragment, binding) {

    lateinit var spotifyAAccountVM: AAccountVM

    override fun onCreate() {
        spotifyAAccountVM = SpotifyAccountVM(fragment.activity, AppPrefs.spotifyUser())
    }

    override fun onCreate(savedInstance: Bundle?) {

    }

    companion object {
        // Request code will be used to verify if result comes from the login activity. Can be set to any integer.
        private val TAG = AccountLinkFragmentVM::class.java.simpleName
    }
}
