package com.startogamu.zikobot.ftu;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.view.View;

import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBaseVM;
import com.spotify.sdk.android.authentication.AuthenticationClient;
import com.spotify.sdk.android.authentication.AuthenticationRequest;
import com.spotify.sdk.android.authentication.AuthenticationResponse;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.databinding.AccountLinkFragmentBinding;

/**
 * Generated by generator-android-template
 */
public class AccountLinkFragmentVM extends DialogBottomSheetBaseVM<AccountLinkFragment, AccountLinkFragmentBinding> {
    // Request code will be used to verify if result comes from the login activity. Can be set to any integer.
    private static final int REQUEST_CODE = 1337;

    private static final String TAG = AccountLinkFragmentVM.class.getSimpleName();

    /***
     * @param fragment
     * @param binding
     */
    public AccountLinkFragmentVM(AccountLinkFragment fragment, AccountLinkFragmentBinding binding) {
        super(fragment, binding);
    }

    @Override
    public void onCreate() {

    }

    public void clickSpotify(View view) {

        AuthenticationRequest.Builder builder =
                new AuthenticationRequest.Builder(fragment.getString(R.string.api_spotify_id),
                        AuthenticationResponse.Type.CODE,
                        fragment.getString(R.string.api_spotify_callback_settings));

        builder.setScopes(new String[]{"streaming"});
        AuthenticationRequest request = builder.build();

        AuthenticationClient.openLoginActivity(fragment.getActivity(), REQUEST_CODE, request);
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstance) {

    }
}
