package com.startogamu.zikobot.home.albums

import com.joxad.easydatabinding.fragment.v4.FragmentBase
import com.startogamu.zikobot.R
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.databinding.AlbumsFragmentBinding
import android.os.Bundle

/**
 * Generated by generator-android-template
 */
class AlbumsFragment : FragmentBase<AlbumsFragmentBinding, AlbumsFragmentVM>() {
    override fun data(): Int {
        return BR.albumsFragmentVM
    }

    override fun layoutResources(): Int {
        return R.layout.albums_fragment
    }

    override fun baseFragmentVM(binding: AlbumsFragmentBinding, savedInstance: Bundle?): AlbumsFragmentVM {
        return AlbumsFragmentVM(this, binding, savedInstance)
    }

    companion object {


        fun newInstance(): AlbumsFragment {
            val args = Bundle()
            val fragment = AlbumsFragment()
            fragment.arguments = args
            return fragment
        }
    }
}
