package com.startogamu.zikobot.home.albums;

import com.joxad.easydatabinding.fragment.v4.FragmentBase;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.AlbumsFragmentBinding;
import android.os.Bundle;

import android.support.annotation.Nullable;
/**
 * Generated by generator-android-template
 */
public class AlbumsFragment extends FragmentBase<AlbumsFragmentBinding, AlbumsFragmentVM> {


  public static AlbumsFragment newInstance() {
       Bundle args = new Bundle();
       AlbumsFragment fragment = new AlbumsFragment();
       fragment.setArguments(args);
       return fragment;
   }
    @Override
    public int data() {
        return BR.albumsFragmentVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.albums_fragment;
    }

    @Override
    public AlbumsFragmentVM baseFragmentVM(AlbumsFragmentBinding binding,@Nullable Bundle savedInstance) {
        return new AlbumsFragmentVM(this, binding,savedInstance);
    }
}
