package com.startogamu.zikobot.home.albums;

import com.joxad.easydatabinding.fragment.v4.FragmentBaseVM;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.AlbumsFragmentBinding;
import com.startogamu.zikobot.home.albums.AlbumsFragment;

import android.os.Bundle;
import android.support.annotation.Nullable;

/**
 * Generated by generator-android-template
 */
public class AlbumsFragmentVM extends FragmentBaseVM<AlbumsFragment, AlbumsFragmentBinding> {

  private static final String TAG = AlbumsFragmentVM.class.getSimpleName();

  /***
    * @param fragment
    * @param binding
    */
   public AlbumsFragmentVM(AlbumsFragment fragment, AlbumsFragmentBinding binding,@Nullable Bundle savedInstance) {
       super(fragment, binding, savedInstance);
   }

   @Override
   public void onCreate(@Nullable Bundle savedInstance) {

   }
}
