package com.startogamu.zikobot.home.albums;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;

import com.joxad.easydatabinding.activity.ActivityBase;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.Constants;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.databinding.AlbumDetailActivityBinding;

/**
 * Generated by generator-android-template
 */
public class AlbumDetailActivity extends ActivityBase<AlbumDetailActivityBinding, AlbumDetailActivityVM> {
    @Override
    public int data() {
        return BR.albumDetailActivityVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.album_detail_activity;
    }

    @Override
    public AlbumDetailActivityVM baseActivityVM(AlbumDetailActivityBinding binding, Bundle savedInstanceState) {
        return new AlbumDetailActivityVM(this, binding, savedInstanceState);
    }

    /***
     * Generate the intent for the activity
     * Use this to start the activity
     */
    public static Intent newInstance(Context context, int albumId) {
        return new Intent(context, AlbumDetailActivity.class)
                .putExtra(Constants.Extra.INSTANCE.getALBUM_ID(), albumId);
    }
}
