package com.startogamu.zikobot.home.albums

import android.databinding.ObservableBoolean
import android.os.Bundle
import com.joxad.androidtemplate.core.log.AppLog
import com.joxad.easydatabinding.fragment.v4.FragmentRecyclerBaseVM
import com.joxad.zikobot.data.db.AlbumManager
import com.joxad.zikobot.data.module.localmusic.manager.LocalMusicManager
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.AlbumsFragmentBinding
import io.reactivex.android.schedulers.AndroidSchedulers
import io.reactivex.disposables.Disposable
import io.reactivex.schedulers.Schedulers

/**
 * Generated by generator-android-template
 */
class AlbumsFragmentVM(fragment: AlbumsFragment, binding: AlbumsFragmentBinding, savedInstance: Bundle?) :
        FragmentRecyclerBaseVM<AlbumVM, AlbumsFragment, AlbumsFragmentBinding>(fragment, binding, savedInstance) {

    lateinit var loading: ObservableBoolean
    private var disposable: Disposable? = null

    override fun itemLayoutResource(): Int {
        return R.layout.album_item
    }

    override fun itemData(): Int {
        return BR.albumVM
    }

    override fun onCreate(savedInstance: Bundle?) {
        super.onCreate(savedInstance)
        loading = ObservableBoolean(true)
        disposable = LocalMusicManager.INSTANCE.synchroDone
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(this::updateList)

    }

    override fun onDestroy() {
        if (disposable != null)
            disposable?.dispose()
        super.onDestroy()
    }

    private fun updateList(done: Boolean) {
        if (!done)
            return
        items.clear()
        AlbumManager.findAll()
                .subscribe({
                    loading.set(false)
                    for (album in it) {
                        items.add(AlbumVM(false, fragment.context, album))
                    }
                }, {
                    loading.set(false)
                    AppLog.INSTANCE.e("albums", it.localizedMessage);
                })
    }

    companion object {
        private val TAG = AlbumsFragmentVM::class.java.simpleName
    }
}
