package com.startogamu.zikobot.home.albums

import android.databinding.ObservableBoolean
import android.os.Bundle
import android.support.v7.widget.GridLayoutManager
import com.joxad.androidtemplate.core.log.AppLog
import com.joxad.easydatabinding.fragment.v4.FragmentRecyclerBaseVM
import com.joxad.zikobot.data.db.AlbumManager
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.AlbumsFragmentBinding

/**
 * Generated by generator-android-template
 */
class AlbumsFragmentVM(fragment: AlbumsFragment, binding: AlbumsFragmentBinding, savedInstance: Bundle?) :
        FragmentRecyclerBaseVM<AlbumVM, AlbumsFragment, AlbumsFragmentBinding>(fragment, binding, savedInstance) {

    lateinit var loading: ObservableBoolean

    override fun itemLayoutResource(): Int {
        return R.layout.album_item
    }

    override fun itemData(): Int {
        return BR.albumVM
    }

    override fun onCreate(savedInstance: Bundle?) {
        super.onCreate(savedInstance)
        loading = ObservableBoolean(true)
        updateList()
        binding.albumsFragmentRV.layoutManager = GridLayoutManager(fragment.context,2)
        binding.fastScroller.setRecyclerView(binding.albumsFragmentRV)
        binding.albumsFragmentRV.addOnScrollListener(binding.fastScroller.onScrollListener)
    }


    private fun updateList() {
        AlbumManager.findAll()
                .subscribe({
                    loading.set(false)
                    for (album in it) {
                        items.add(AlbumVM(false, fragment.context, album))
                    }
                }, {
                    loading.set(false)
                    AppLog.INSTANCE.e("albums", it.localizedMessage);
                })
    }


    companion object {
        private val TAG = AlbumsFragmentVM::class.java.simpleName
    }
}
