package com.startogamu.zikobot.home.addtracktoplaylist

import android.databinding.ObservableArrayList
import android.databinding.ObservableBoolean
import android.os.Bundle
import android.view.View
import android.widget.Toast
import com.joxad.androidtemplate.core.log.AppLog
import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBaseVM
import com.joxad.zikobot.data.AppPrefs
import com.joxad.zikobot.data.db.PlaylistManager
import com.joxad.zikobot.data.db.model.ZikoPlaylist
import com.joxad.zikobot.data.module.accounts.AccountManager
import com.joxad.zikobot.data.module.spotify_api.manager.SpotifyApiManager
import com.raizlabs.android.dbflow.rx2.kotlinextensions.list
import com.startogamu.zikobot.BR
import com.startogamu.zikobot.NavigationManager
import com.startogamu.zikobot.R
import com.startogamu.zikobot.databinding.AddTrackToPlaylistFragmentBinding
import com.startogamu.zikobot.databinding.SpotifySyncPlaylistsFragmentBinding
import com.startogamu.zikobot.home.playlists.PlaylistVM
import com.startogamu.zikobot.home.sync.SpotifySyncPlaylistsFragment
import me.tatarka.bindingcollectionadapter2.ItemBinding

/**
 * Generated by generator-android-template
 */
class AddTrackToPlaylistFragmentVM(fragment: AddTrackToPlaylistFragment, binding: AddTrackToPlaylistFragmentBinding) : DialogBottomSheetBaseVM<AddTrackToPlaylistFragment, AddTrackToPlaylistFragmentBinding>(fragment, binding) {


    var itemBinding = ItemBinding.of<PlaylistVM>(BR.playlistVM, R.layout.playlist_item)
    lateinit var items: ObservableArrayList<PlaylistVM>
    lateinit var loading: ObservableBoolean
    override fun onCreate() {

        items = ObservableArrayList()
        loading = ObservableBoolean(false)

            loadData()

    }

    private fun loadData() {
        loading.set(true)
        PlaylistManager.INSTANCE.findAll().list {
            for (zikoP in it) {
                items.add(PlaylistVM(false, fragment.activity, zikoP))
            }
            loading.set(false)
        }

    }

    override fun onCreate(savedInstance: Bundle?) {

    }

    companion object {

        val TAG = AddTrackToPlaylistFragmentVM::class.java.simpleName
    }
}