package com.startogamu.zikobot.home.addtracktoplaylist;

import android.app.Dialog;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.BottomSheetBehavior;
import android.support.design.widget.BottomSheetDialog;
import android.widget.FrameLayout;

import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBase;
import com.joxad.zikobot.data.db.model.ZikoTrack;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.Constants;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.databinding.AddTrackToPlaylistFragmentBinding;
import com.startogamu.zikobot.databinding.SpotifySyncPlaylistsFragmentBinding;
import com.startogamu.zikobot.home.sync.SpotifySyncPlaylistsFragmentVM;

/**
 * Generated by generator-android-template
 */
public class AddTrackToPlaylistFragment extends DialogBottomSheetBase<AddTrackToPlaylistFragmentBinding, AddTrackToPlaylistFragmentVM> {


    public static AddTrackToPlaylistFragment newInstance(ZikoTrack track) {
        Bundle args = new Bundle();
        AddTrackToPlaylistFragment fragment = new AddTrackToPlaylistFragment();
        args.putLong(Constants.Extra.INSTANCE.getTRACK_ID(), track.getId());
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public int data() {
        return BR.fragmentVM;
    }

    @Override
    public int layoutResources() {
        return R.layout.add_track_to_playlist_fragment;
    }

    @Override
    public AddTrackToPlaylistFragmentVM baseFragmentVM(AddTrackToPlaylistFragmentBinding binding) {
        return new AddTrackToPlaylistFragmentVM(this, binding);
    }

    @NonNull
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        BottomSheetDialog dialog = (BottomSheetDialog) super.onCreateDialog(savedInstanceState);
        dialog.setOnShowListener(dialog1 -> {
            BottomSheetDialog d = (BottomSheetDialog) dialog1;
            FrameLayout bottomSheet = (FrameLayout) d.findViewById(android.support.design.R.id.design_bottom_sheet);
            BottomSheetBehavior<FrameLayout> bot = BottomSheetBehavior.from(bottomSheet);
            bot.setState(BottomSheetBehavior.STATE_EXPANDED);

        });
        return dialog;
    }
}
