package com.startogamu.zikobot.settings;

import android.os.Bundle;
import android.support.annotation.Nullable;

import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBaseVM;
import com.startogamu.zikobot.R;
import com.startogamu.zikobot.BR;
import com.startogamu.zikobot.databinding.SettingsBottomFragmentBinding;
import com.startogamu.zikobot.settings.SettingsBottomFragment;

/**
 * Generated by generator-android-template
 */
public class SettingsBottomFragmentVM extends DialogBottomSheetBaseVM<SettingsBottomFragment, SettingsBottomFragmentBinding> {

  private static final String TAG = SettingsBottomFragmentVM.class.getSimpleName();

  /***
    * @param fragment
    * @param binding
    */
   public SettingsBottomFragmentVM(SettingsBottomFragment fragment, SettingsBottomFragmentBinding binding) {
       super(fragment, binding);
   }

   @Override
   public void onCreate() {

   }

    @Override
    public void onCreate(@Nullable Bundle savedInstance) {

    }
}
