package com.startogamu.zikobot.settings

import android.os.Bundle
import android.view.View
import com.joxad.androidtemplate.core.log.AppLog
import com.joxad.easydatabinding.bottomsheet.DialogBottomSheetBaseVM
import com.joxad.zikobot.data.db.TrackManager
import com.startogamu.zikobot.Constants
import com.startogamu.zikobot.databinding.SettingsBottomFragmentBinding
import com.startogamu.zikobot.home.track.TrackVM

/**
 * Generated by generator-android-template
 */
class SettingsBottomFragmentVM
/***
 * @param fragment
 * @param binding
 */
(fragment: SettingsBottomFragment, binding: SettingsBottomFragmentBinding) : DialogBottomSheetBaseVM<SettingsBottomFragment, SettingsBottomFragmentBinding>(fragment, binding) {
    public lateinit var trackVM: TrackVM
    override fun onCreate() {

        TrackManager.findOne(fragment.arguments.getLong(Constants.Extra.TRACK_ID))
                .querySingle()
                .subscribe({
                    trackVM = TrackVM(fragment.context, it)
                }, {
                    AppLog.INSTANCE.d(TAG, it.localizedMessage)
                })

    }

    override fun onCreate(savedInstance: Bundle?) {

    }


    fun showArtistPage(view: View) {
        trackVM.showArtistPage(view)
    }


    fun addTrackToPlaylist(view: View) {
        trackVM.addToPlaylist(view)
    }

    companion object {

        private val TAG = SettingsBottomFragmentVM::class.java.simpleName
    }
}
