package com.startogamu.zikobot.home.track

import android.content.Context
import android.databinding.Bindable

import com.joxad.easydatabinding.base.BaseVM
import com.joxad.zikobot.data.db.model.ZikoTrack

/**
 * Generated by generator-android-template
 * <!!!!!> You have to replace the Object to your POJO class that will be handled in the VM <!!!!!>
 */
class TrackVM
/***
 * @param context
 * *
 * @param model
 */
(context: Context, model: ZikoTrack) : BaseVM<ZikoTrack>(context, model) {

    override fun onCreate() {
        if (model.zikoAlbum != null)
            model.zikoAlbum.load()
        if (model.zikoArtist != null)
            model.zikoArtist.load()
        notifyChange()
    }

    val title: String
        @Bindable
        get() = model.name

    val image: String?
        @Bindable
        get() {
            if (model.zikoAlbum != null)
                return model.zikoAlbum.image
            return null
        }

    val artistName: String
        @Bindable
        get() {
            if (model.zikoArtist != null)
                return model.zikoArtist.name
            return "Unknown artist"
        }

    companion object {
        private val TAG = TrackVM::class.java.simpleName
    }
}
